#!/usr/bin/env bash
# generate-build-index.sh — Aggregate per-plugin build metadata into build-index.json
# and generate a human-readable docs/build-index.md.
#
# Usage: ./scripts/generate-build-index.sh [--metadata-dir DIR] [--output FILE] [--docs-output FILE]
#
# In CI, this script reads individual JSON metadata files produced by each matrix job.
# Locally, it can generate a placeholder index from plugins.yaml.
set -euo pipefail

# ─── Colors ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; }

# ─── Args ─────────────────────────────────────────────────────────────────────
METADATA_DIR="${1:-/tmp/build-metadata}"
OUTPUT="${2:-build-index.json}"
DOCS_OUTPUT="${3:-docs/build-index.md}"
CI_RUN_URL="${GITHUB_SERVER_URL:-https://github.com}/${GITHUB_REPOSITORY:-local/dev}/actions/runs/${GITHUB_RUN_ID:-0}"

# ─── Dependency check ─────────────────────────────────────────────────────────
for cmd in jq; do
  if ! command -v "$cmd" &>/dev/null; then
    error "Required command '$cmd' not found."
    exit 1
  fi
done

# ─── Aggregate metadata ──────────────────────────────────────────────────────
info "Aggregating build metadata from ${METADATA_DIR}/"

GENERATED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

if [[ -d "$METADATA_DIR" ]] && ls "$METADATA_DIR"/*.json &>/dev/null; then
  # Merge all per-plugin JSON files into the build index
  IMAGES=$(jq -s '.' "$METADATA_DIR"/*.json)
else
  info "No metadata files found in ${METADATA_DIR}. Creating empty index."
  IMAGES="[]"
fi

# Build the index JSON
jq -n \
  --arg generated_at "$GENERATED_AT" \
  --arg ci_run_url "$CI_RUN_URL" \
  --argjson images "$IMAGES" \
  '{
    generated_at: $generated_at,
    ci_run_url: $ci_run_url,
    images: $images
  }' > "$OUTPUT"

info "Build index written to ${OUTPUT}"

# ─── Generate Markdown table ─────────────────────────────────────────────────
info "Generating docs at ${DOCS_OUTPUT}"

mkdir -p "$(dirname "$DOCS_OUTPUT")"

cat > "$DOCS_OUTPUT" << 'HEADER'
# Build Index

> **This file is auto-generated by CI.** Do not edit manually.
> Last updated by [generate-build-index.sh](../scripts/generate-build-index.sh).

## Published Images

HEADER

IMAGE_COUNT=$(jq '.images | length' "$OUTPUT")

if [[ "$IMAGE_COUNT" -eq 0 ]]; then
  echo "_No images have been published yet._" >> "$DOCS_OUTPUT"
else
  # Table header
  echo "| Plugin | Kind | Version | Image | Upstream Tag | Upstream Commit | Built |" >> "$DOCS_OUTPUT"
  echo "|--------|------|---------|-------|-------------|-----------------|-------|" >> "$DOCS_OUTPUT"

  # Table rows
  jq -r '.images[] | "| \(.plugin_name) | \(.plugin_kind) | \(.version) | `\(.image)` | \(.upstream_tag) | `\(.upstream_commit[0:12])` | \(.build_timestamp) |"' "$OUTPUT" >> "$DOCS_OUTPUT"
fi

cat >> "$DOCS_OUTPUT" << FOOTER

## Artifact

The machine-readable build index (\`build-index.json\`) is available as a workflow artifact
from each [publish run](${CI_RUN_URL}).

**Schema**: [\`schemas/build-index.schema.json\`](../schemas/build-index.schema.json)
FOOTER

info "Documentation updated at ${DOCS_OUTPUT}"
info "Build index generation complete ✓"
